#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
        # Custom Settings
        role=${CONTAINER_ROLE:-app}

        SAIL_VERSION=$(php --version | grep -oP '(?<=PHP )\d+\.\d+');

        echo "Environment: ${APP_ENV}"
        echo "PHP: ${SAIL_VERSION}"
        echo "ROLE: ${role}"

        if [ "$role" = "app" ]; then
            exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
        elif [ "$role" = "scheduler" ]; then
            cp /var/www/html/docker/${SAIL_VERSION}/scheduler.conf /etc/supervisor/conf.d/scheduler.conf
            exec /usr/bin/supervisord -c /etc/supervisor/conf.d/scheduler.conf
         elif [ "$role" = "queue" ]; then
            exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
        elif [ "$role" = "horizon" ]; then
            exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
        elif [ "$role" = "traccar-listening" ]; then
            exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
        else
            echo "Could not match the container role \"$role\""
            exit 1
        fi
        # Custom Settings
fi

